/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeIndexRouteImport } from './routes/youtube.index'
import { Route as WorkshopsIndexRouteImport } from './routes/workshops.index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkshopsSlugRouteImport } from './routes/workshops.$slug'
import { Route as ToolsToolSlugRouteImport } from './routes/tools/$toolSlug'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as DebugMigrateWorkshopsRouteImport } from './routes/debug.migrate-workshops'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminYoutubeIndexRouteImport } from './routes/admin/youtube/index'
import { Route as AdminWorkshopsIndexRouteImport } from './routes/admin/workshops/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as CoursesCourseSlugLessonSlugRouteImport } from './routes/courses.$courseSlug.$lessonSlug'
import { Route as AdminWorkshopsCreateRouteImport } from './routes/admin/workshops/create'
import { Route as AdminWorkshopsLayoutRouteImport } from './routes/admin/workshops/_layout'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPostsLayoutRouteImport } from './routes/admin/posts/_layout'
import { Route as AdminCoursesCreateRouteImport } from './routes/admin/courses/create'
import { Route as AdminCoursesLayoutRouteImport } from './routes/admin/courses/_layout'
import { Route as AdminWorkshopsIdEditRouteImport } from './routes/admin/workshops/$id/edit'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin/posts/$id/edit'
import { Route as AdminCoursesIdLessonsRouteImport } from './routes/admin/courses/$id/lessons'
import { Route as AdminCoursesIdEditRouteImport } from './routes/admin/courses/$id/edit'

const AdminRouteImport = createFileRoute('/admin')()
const AdminWorkshopsRouteImport = createFileRoute('/admin/workshops')()
const AdminPostsRouteImport = createFileRoute('/admin/posts')()
const AdminCoursesRouteImport = createFileRoute('/admin/courses')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkshopsRoute = AdminWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const YoutubeIndexRoute = YoutubeIndexRouteImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsIndexRoute = WorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorkshopsSlugRoute = WorkshopsSlugRouteImport.update({
  id: '/workshops/$slug',
  path: '/workshops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolSlugRoute = ToolsToolSlugRouteImport.update({
  id: '/tools/$toolSlug',
  path: '/tools/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugMigrateWorkshopsRoute = DebugMigrateWorkshopsRouteImport.update({
  id: '/debug/migrate-workshops',
  path: '/debug/migrate-workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYoutubeIndexRoute = AdminYoutubeIndexRouteImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkshopsIndexRoute = AdminWorkshopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorkshopsRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const CoursesCourseSlugLessonSlugRoute =
  CoursesCourseSlugLessonSlugRouteImport.update({
    id: '/courses/$courseSlug/$lessonSlug',
    path: '/courses/$courseSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWorkshopsCreateRoute = AdminWorkshopsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminWorkshopsRoute,
} as any)
const AdminWorkshopsLayoutRoute = AdminWorkshopsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminWorkshopsRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminPostsLayoutRoute = AdminPostsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminCoursesCreateRoute = AdminCoursesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesLayoutRoute = AdminCoursesLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminWorkshopsIdEditRoute = AdminWorkshopsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminWorkshopsRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPostsRoute,
} as any)
const AdminCoursesIdLessonsRoute = AdminCoursesIdLessonsRouteImport.update({
  id: '/$id/lessons',
  path: '/$id/lessons',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesIdEditRoute = AdminCoursesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminLayoutRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/debug/migrate-workshops': typeof DebugMigrateWorkshopsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/admin/courses': typeof AdminCoursesLayoutRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/posts': typeof AdminPostsLayoutRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/workshops': typeof AdminWorkshopsLayoutRoute
  '/admin/workshops/create': typeof AdminWorkshopsCreateRoute
  '/courses/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/workshops/': typeof AdminWorkshopsIndexRoute
  '/admin/youtube': typeof AdminYoutubeIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/admin/courses/$id/lessons': typeof AdminCoursesIdLessonsRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/workshops/$id/edit': typeof AdminWorkshopsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminIndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/debug/migrate-workshops': typeof DebugMigrateWorkshopsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/workshops': typeof WorkshopsIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/workshops': typeof AdminWorkshopsIndexRoute
  '/admin/workshops/create': typeof AdminWorkshopsCreateRoute
  '/courses/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
  '/admin/youtube': typeof AdminYoutubeIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/admin/courses/$id/lessons': typeof AdminCoursesIdLessonsRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/workshops/$id/edit': typeof AdminWorkshopsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/debug/migrate-workshops': typeof DebugMigrateWorkshopsRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/workshops/$slug': typeof WorkshopsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/workshops/': typeof WorkshopsIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/courses/_layout': typeof AdminCoursesLayoutRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/posts/_layout': typeof AdminPostsLayoutRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/workshops': typeof AdminWorkshopsRouteWithChildren
  '/admin/workshops/_layout': typeof AdminWorkshopsLayoutRoute
  '/admin/workshops/create': typeof AdminWorkshopsCreateRoute
  '/courses/$courseSlug/$lessonSlug': typeof CoursesCourseSlugLessonSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/workshops/': typeof AdminWorkshopsIndexRoute
  '/admin/youtube/': typeof AdminYoutubeIndexRoute
  '/admin/courses/$id/edit': typeof AdminCoursesIdEditRoute
  '/admin/courses/$id/lessons': typeof AdminCoursesIdLessonsRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/admin/workshops/$id/edit': typeof AdminWorkshopsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/courses/$slug'
    | '/debug/migrate-workshops'
    | '/posts/$slug'
    | '/tools/$toolSlug'
    | '/workshops/$slug'
    | '/admin/'
    | '/courses'
    | '/posts'
    | '/tools'
    | '/workshops'
    | '/youtube'
    | '/admin/courses'
    | '/admin/courses/create'
    | '/admin/posts'
    | '/admin/posts/create'
    | '/admin/workshops'
    | '/admin/workshops/create'
    | '/courses/$courseSlug/$lessonSlug'
    | '/admin/courses/'
    | '/admin/posts/'
    | '/admin/workshops/'
    | '/admin/youtube'
    | '/admin/courses/$id/edit'
    | '/admin/courses/$id/lessons'
    | '/admin/posts/$id/edit'
    | '/admin/workshops/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/courses/$slug'
    | '/debug/migrate-workshops'
    | '/posts/$slug'
    | '/tools/$toolSlug'
    | '/workshops/$slug'
    | '/courses'
    | '/posts'
    | '/tools'
    | '/workshops'
    | '/youtube'
    | '/admin/courses'
    | '/admin/courses/create'
    | '/admin/posts'
    | '/admin/posts/create'
    | '/admin/workshops'
    | '/admin/workshops/create'
    | '/courses/$courseSlug/$lessonSlug'
    | '/admin/youtube'
    | '/admin/courses/$id/edit'
    | '/admin/courses/$id/lessons'
    | '/admin/posts/$id/edit'
    | '/admin/workshops/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/admin'
    | '/admin/_layout'
    | '/courses/$slug'
    | '/debug/migrate-workshops'
    | '/posts/$slug'
    | '/tools/$toolSlug'
    | '/workshops/$slug'
    | '/admin/'
    | '/courses/'
    | '/posts/'
    | '/tools/'
    | '/workshops/'
    | '/youtube/'
    | '/admin/courses'
    | '/admin/courses/_layout'
    | '/admin/courses/create'
    | '/admin/posts'
    | '/admin/posts/_layout'
    | '/admin/posts/create'
    | '/admin/workshops'
    | '/admin/workshops/_layout'
    | '/admin/workshops/create'
    | '/courses/$courseSlug/$lessonSlug'
    | '/admin/courses/'
    | '/admin/posts/'
    | '/admin/workshops/'
    | '/admin/youtube/'
    | '/admin/courses/$id/edit'
    | '/admin/courses/$id/lessons'
    | '/admin/posts/$id/edit'
    | '/admin/workshops/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesSlugRoute: typeof CoursesSlugRoute
  DebugMigrateWorkshopsRoute: typeof DebugMigrateWorkshopsRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ToolsToolSlugRoute: typeof ToolsToolSlugRoute
  WorkshopsSlugRoute: typeof WorkshopsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
  YoutubeIndexRoute: typeof YoutubeIndexRoute
  CoursesCourseSlugLessonSlugRoute: typeof CoursesCourseSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshops': {
      id: '/admin/workshops'
      path: '/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminWorkshopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/workshops/$slug': {
      id: '/workshops/$slug'
      path: '/workshops/$slug'
      fullPath: '/workshops/$slug'
      preLoaderRoute: typeof WorkshopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolSlug': {
      id: '/tools/$toolSlug'
      path: '/tools/$toolSlug'
      fullPath: '/tools/$toolSlug'
      preLoaderRoute: typeof ToolsToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/migrate-workshops': {
      id: '/debug/migrate-workshops'
      path: '/debug/migrate-workshops'
      fullPath: '/debug/migrate-workshops'
      preLoaderRoute: typeof DebugMigrateWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/youtube/': {
      id: '/admin/youtube/'
      path: '/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workshops/': {
      id: '/admin/workshops/'
      path: '/'
      fullPath: '/admin/workshops/'
      preLoaderRoute: typeof AdminWorkshopsIndexRouteImport
      parentRoute: typeof AdminWorkshopsRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/courses/$courseSlug/$lessonSlug': {
      id: '/courses/$courseSlug/$lessonSlug'
      path: '/courses/$courseSlug/$lessonSlug'
      fullPath: '/courses/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workshops/create': {
      id: '/admin/workshops/create'
      path: '/create'
      fullPath: '/admin/workshops/create'
      preLoaderRoute: typeof AdminWorkshopsCreateRouteImport
      parentRoute: typeof AdminWorkshopsRoute
    }
    '/admin/workshops/_layout': {
      id: '/admin/workshops/_layout'
      path: '/workshops'
      fullPath: '/admin/workshops'
      preLoaderRoute: typeof AdminWorkshopsLayoutRouteImport
      parentRoute: typeof AdminWorkshopsRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/posts/_layout': {
      id: '/admin/posts/_layout'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsLayoutRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/courses/create': {
      id: '/admin/courses/create'
      path: '/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminCoursesCreateRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/_layout': {
      id: '/admin/courses/_layout'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesLayoutRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/workshops/$id/edit': {
      id: '/admin/workshops/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/workshops/$id/edit'
      preLoaderRoute: typeof AdminWorkshopsIdEditRouteImport
      parentRoute: typeof AdminWorkshopsRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/admin/courses/$id/lessons': {
      id: '/admin/courses/$id/lessons'
      path: '/$id/lessons'
      fullPath: '/admin/courses/$id/lessons'
      preLoaderRoute: typeof AdminCoursesIdLessonsRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$id/edit': {
      id: '/admin/courses/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/courses/$id/edit'
      preLoaderRoute: typeof AdminCoursesIdEditRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesLayoutRoute: typeof AdminCoursesLayoutRoute
  AdminCoursesCreateRoute: typeof AdminCoursesCreateRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminCoursesIdEditRoute: typeof AdminCoursesIdEditRoute
  AdminCoursesIdLessonsRoute: typeof AdminCoursesIdLessonsRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesLayoutRoute: AdminCoursesLayoutRoute,
  AdminCoursesCreateRoute: AdminCoursesCreateRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminCoursesIdEditRoute: AdminCoursesIdEditRoute,
  AdminCoursesIdLessonsRoute: AdminCoursesIdLessonsRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsLayoutRoute: typeof AdminPostsLayoutRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsLayoutRoute: AdminPostsLayoutRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminWorkshopsRouteChildren {
  AdminWorkshopsLayoutRoute: typeof AdminWorkshopsLayoutRoute
  AdminWorkshopsCreateRoute: typeof AdminWorkshopsCreateRoute
  AdminWorkshopsIndexRoute: typeof AdminWorkshopsIndexRoute
  AdminWorkshopsIdEditRoute: typeof AdminWorkshopsIdEditRoute
}

const AdminWorkshopsRouteChildren: AdminWorkshopsRouteChildren = {
  AdminWorkshopsLayoutRoute: AdminWorkshopsLayoutRoute,
  AdminWorkshopsCreateRoute: AdminWorkshopsCreateRoute,
  AdminWorkshopsIndexRoute: AdminWorkshopsIndexRoute,
  AdminWorkshopsIdEditRoute: AdminWorkshopsIdEditRoute,
}

const AdminWorkshopsRouteWithChildren = AdminWorkshopsRoute._addFileChildren(
  AdminWorkshopsRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminWorkshopsRoute: typeof AdminWorkshopsRouteWithChildren
  AdminYoutubeIndexRoute: typeof AdminYoutubeIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminWorkshopsRoute: AdminWorkshopsRouteWithChildren,
  AdminYoutubeIndexRoute: AdminYoutubeIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesSlugRoute: CoursesSlugRoute,
  DebugMigrateWorkshopsRoute: DebugMigrateWorkshopsRoute,
  PostsSlugRoute: PostsSlugRoute,
  ToolsToolSlugRoute: ToolsToolSlugRoute,
  WorkshopsSlugRoute: WorkshopsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
  YoutubeIndexRoute: YoutubeIndexRoute,
  CoursesCourseSlugLessonSlugRoute: CoursesCourseSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
